"""TCL configuration file writer for HLS tools.

Maps SynthesisParams to TCL directives across three config files:
  - project.tt2.tcl  : clock period, DPO mode
  - block.config     : unroll, pipeline, partition, flatten, inline, etc.
  - block.procs.tcl  : clock slack

Backs up original files before modification.
"""

import os
import shutil
from datetime import datetime
from typing import Dict

from aiv_dse.llm.models import SynthesisParams


def backup_tcl_files(project_dir: str) -> Dict[str, str]:
    """Create timestamped backups of TCL config files.

    Returns dict mapping original path to backup path.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backups: Dict[str, str] = {}

    for filename in ("project.tt2.tcl", "block.config", "block.procs.tcl"):
        src = os.path.join(project_dir, filename)
        if os.path.exists(src):
            backup = os.path.join(project_dir, f"{filename}.backup_{timestamp}")
            shutil.copy2(src, backup)
            backups[src] = backup

    return backups


def write_project_tt2_tcl(project_dir: str, params: SynthesisParams) -> None:
    """Write project.tt2.tcl with clock and DPO settings."""
    path = os.path.join(project_dir, "project.tt2.tcl")

    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            lines = f.readlines()
    else:
        lines = ["# Auto-generated by AIV-DSE\n"]

    # Update or append clock_period
    clock_line = f"set_attr clock_period {{{params.clock_period_ns}}}\n"
    updated = False
    for i, line in enumerate(lines):
        if "set_attr clock_period" in line:
            lines[i] = clock_line
            updated = True
            break
    if not updated:
        lines.append(clock_line)

    # Update or append dpo_mode (only if not "none")
    # First remove any existing dpo_mode line
    lines = [ln for ln in lines if "set_attr dpo_mode" not in ln]
    if params.dpo_mode != "none":
        lines.append(f"set_attr dpo_mode {{{params.dpo_mode}}}\n")

    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)


def write_block_config(project_dir: str, params: SynthesisParams) -> None:
    """Write block.config with synthesis directives."""
    path = os.path.join(project_dir, "block.config")

    lines = [
        "# Auto-generated by AIV-DSE\n",
        "\n",
        f"# Unroll factor: {params.unroll_factor}\n",
        f"set_directive_unroll -factor {params.unroll_factor} main_loop\n",
        "\n",
        f"# Pipeline depth (II): {params.pipeline_depth}\n",
        f"set_directive_pipeline -II {params.pipeline_depth} main_loop\n",
        "\n",
        f"# Array partition factor: {params.array_partition_factor}\n",
        f"set_directive_array_partition -factor {params.array_partition_factor} coeff_array\n",
        "\n",
    ]

    if params.flatten:
        lines.append("set_directive_inline all -recursive\n")
    if params.inline:
        lines.append("set_directive_inline all\n")
    if params.loop_merge:
        lines.append("set_directive_loop_merge main_loop\n")
    if params.bitwidth_reduce:
        lines.append("set_directive_bitwidth_opt all\n")
    if params.resource_sharing:
        lines.append("set_directive_resource_sharing all\n")

    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)


def write_block_procs_tcl(project_dir: str, params: SynthesisParams) -> None:
    """Write block.procs.tcl with clock slack."""
    path = os.path.join(project_dir, "block.procs.tcl")

    lines = [
        "# Auto-generated by AIV-DSE\n",
        "\n",
        f"# Clock slack: {params.clock_slack_ns} ns\n",
        f"set clock_slack {{{params.clock_slack_ns}}}\n",
    ]

    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)


def write_tcl_config(
    params: SynthesisParams, project_dir: str
) -> Dict[str, str]:
    """Write all TCL config files for HLS synthesis.

    Returns dict mapping original file paths to backup paths.
    """
    backups = backup_tcl_files(project_dir)

    write_project_tt2_tcl(project_dir, params)
    write_block_config(project_dir, params)
    write_block_procs_tcl(project_dir, params)

    return backups
